server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    #是否把自己作为服务注册到其它服务注册中心
    register-with-eureka: false
    #是否从其它服务注册中心同步服务列表
    fetch-registry: false
spring:
  application:
    name: eureka-server
  security:
    user:
      name: root
      password: root
